# Start with docker-compose up

es1:
  image: elasticsearch:2.3
  ports:
  - "9200:9200"
es2:
  image: elasticsearch:2.3
es3:
  image: elasticsearch:2.3
newrelic:
  image: s12v/newrelic-elasticsearch
  links:
    - es1:elasticsearch
  environment:
    - ES_HOST=elasticsearch
    - NEW_RELIC_LICENSE_KEY=itsasecret
